### PR TITLE
Example glfw vulkan

### PR DESCRIPTION
**Pull request by ParticlePeter**
As the title says, working glfw-vulkan backend.

Regarding
> Wait for https://issues.dlang.org/show_bug.cgi?id=20905 to get fixed.

I think I can help with that, but I am not able to reproduce the original issue within your codebase. Do you have any example?

Great work, btw! Was on my long time to do list, but to lazy so far. Hoped that at some point we might be able to auto-convert the cpp code. Tried several existing approaches, none worked satisfyingly.

### CODE REVIEW

**Comment by KytoDragon** [comment]
Hello @ParticlePeter,
sorry for not replying sooner, I didn't have notifications set up and only now saw your pull request.
If you could rebase your changes on the newest version (just merged 1.83), I would by happy to accept them.

Regarding issue https://issues.dlang.org/show_bug.cgi?id=20905: The following example still fails in the newest compiler version:
```
struct Foo {
    my_type index;  
}

static if(true) {
    alias my_type = int;
}
```
It would be great if you could help find or even fix the bug.

I do use a small tool I wrote to automatically translate most of the code via very simple text search-and-replace.

**Comment by ParticlePeter** [comment]
Hi @KytoDragon,
wasn't observing myself. I'll upgrade and rebase as soon as possible.
About the Bug, I am not sure if I fully understand the problem. I read the bugzilla issue, but I cannot find any occurrence of this pattern in d_imgui code base. Can you point me to such occurrence in your code?

**Comment by KytoDragon** [comment]
Hallo @ParticlePeter,
if you search through the code for the following comment, you should find all occurrences of this problem:
```// TODO D_IMGUI: See bug https://issues.dlang.org/show_bug.cgi?id=20905```
Right now the code that is supposed to be inside the static if block is always just below it. If you move the code inside the static if it breaks compilation with "undefined identifier" errors.

**Comment by ParticlePeter** [comment]
I re-based to the current version, the example runs, but the latets VulkanSDK tells about some error, which I'll fix next. However, feel free to test it. Also looking into the d-bug.

**Comment by ParticlePeter** [comment]
Hi @KytoDragon,
I tried several tricks, string import, mixin templates in several variations, without success. But I doubt that this DLang issue will be fixed, at least not soon. I have two suggestions, guess you had similar ideas:

1. Turn all the enums in d_imgui.imconfig into versions. All the enums are false by default, if the user wants to enable any, he just needs to specify them in the build command or dub project file. Keep the imconfig module, for the ImTextureID and other user alias as well as user defined handlers.
2. Move all conditionally compiled code depending on the imconfig enums into imconfig. This would deviate from the original imguie, but would work.

I can prepare a PR if you like any of these options.

**Comment by KytoDragon** [comment]
Merged

**Pull request closed without merging**
