### PR TITLE
fix builds on non-windows systems

### PR DESCRIPTION
**Pull request by Herringway**
Just some small fixes that block builds on non-windows systems.

### CODE REVIEW

**Comment by Herringway** [comment]
@KytoDragon Hey, can you take a look at this?

**Comment by KytoDragon** [comment]
@Herringway Sorry for the wait. I will release a new version in a couple days.

**Comment by Herringway** [comment]
Thanks so much!

**Comment by Herringway** [comment]
@KytoDragon For some reason, the new tags aren't being picked up by dub... Any idea why?

**Comment by KytoDragon** [comment]
@Herringway Thanks for the info. The automatic update got stuck somehow, I triggered a manual update and all the new versions are available.

**Pull request merged**
